apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s
  labels:
    app: java-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-k8s
  template:
    metadata:
      labels:
        app: java-k8s
    spec:
      containers:
      - name: java-k8s
        image: benisrael/java-k8s:12
        ports:
        - containerPort: 8080